title: iLOX Docs
description: InterLocking Orthogonal eXtrusions: An OpenSCAD Library for Designing Tessellated Interlocking Surface Geometry for 3D Printing.
theme: just-the-docs
color_scheme: openscad-dark

aux_links:
  Template Repository: https://github.com/CameronBrooks11/just-the-docs-template-openscad